profile/subsystem/memory.py: Check the non-existing svg
For some reason that the corresponding .svg is not captured. Then, the
date from the meminfo cannot find the .svg. The reason could be the
easy-flamegraph tool is stopped after the meminfo is captured and before
the .svg is generated.

Traceback (most recent call last):
  File "./profile/dashboard.py", line 11, in <module>
    tab_memory = memory_tab()
  File "/home/vin/os/easy-flamegraph/profile/subsystem/memory.py", line 373, in memory_tab
    [plot_meminfo(link_table), plot_vmstat(link_table)],
  File "/home/vin/os/easy-flamegraph/profile/subsystem/memory.py", line 180, in plot_meminfo
    df_meminfo['link'] = link_list(df_meminfo, link_table)
  File "/home/vin/os/easy-flamegraph/profile/subsystem/memory.py", line 64, in link_list
    links.append(link_table[numeric_date[:-2]])
KeyError: '202105211833'

Signed-off-by: Gavin Guo <gavin.guo@canonical.com>